language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker --version  # document the version travis is using
  - docker build -t Innablr-nodejs-sample .
 # - docker login -u balu2044 -p @Balu2044
  - docker images
  - docker tag Innablr-nodejs-sample balu2044/innablrdemo:v1
  - docker push balu2044/innablrdemo:v1
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $github_token
#  local_dir: build
#  on:
#    branch: master
 
